### ISSUE TITLE
RunTimeError

### ISSUE THREAD

**Issue by tohkazsx** [LunaBlack/KGAT-pytorch#12]
I run the code with  yelp2018 dataset ，but  an error occurred in epoch2

2021-03-22 17:14:01,766 - root - INFO - KG Training: Epoch 0002 Total Iter 2719 | Total Time 241.7s | Iter Mean Loss 0.0315
2021-03-22 17:14:01,766 - root - INFO - CF + KG Training: Epoch 0002 | Total Time 470.4s
Traceback (most recent call last):
  File "main_kgat.py", line 286, in <module>
    train(args)
  File "main_kgat.py", line 196, in train
    _, precision, recall, ndcg = evaluate(model, train_graph, data.train_user_dict, data.test_user_dict, user_ids_batches, item_ids, args.K)
  File "main_kgat.py", line 41, in evaluate
    cf_scores_batch = model('predict', train_graph, user_ids_batch, item_ids)       # (n_batch_users, n_eval_items)
  File "/opt/miniconda3/envs/zsx_dgl/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user18/zsx/GraduationProj/KGAT-pytorch/model/KGAT.py", line 224, in forward
    return self.cf_score(mode, *input)
  File "/home/user18/zsx/GraduationProj/KGAT-pytorch/model/KGAT.py", line 188, in cf_score
    cf_score = torch.matmul(user_embed, item_embed.transpose(0, 1))    # (n_eval_users, n_eval_items)

RuntimeError: CUDA out of memory. Tried to allocate 1.70 GiB (GPU 0; 31.71 GiB total capacity; 10.63 GiB already allocated; 597.12 MiB free; 12.47 GiB reserved in total by PyTorch)

**Comment by frostmourne78** [comment]
hi Did you finally solve the problem？

**Comment by qql-Kenneth** [comment]
same error

**Comment by qql-Kenneth** [comment]
i run code with  amazon-book, which using more than 30G
