### ISSUE TITLE
cannot run with GPU

### ISSUE THREAD

**Issue by YiSandy** [LunaBlack/KGAT-pytorch#14]
这个代码用cpu可以正常的跑，但是用GPU就会报下面的错，想知道怎么解决，有没有小伙伴遇到了同样的问题

Traceback (most recent call last):
  File "main_kgat.py", line 287, in <module>
    train(args)
  File "main_kgat.py", line 141, in train
    att = model('calc_att', train_graph)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/KGAT-pytorch/model/KGAT.py", line 218, in forward
    return self.compute_attention(*input)
  File "/data/KGAT-pytorch/model/KGAT.py", line 125, in compute_attention
    g.apply_edges(self.att_score, edge_idxs)
  File "/opt/conda/lib/python3.7/site-packages/dgl/graph.py", line 2148, in apply_edges
    Runtime.run(prog)
  File "/opt/conda/lib/python3.7/site-packages/dgl/runtime/runtime.py", line 11, in run
    exe.run()
  File "/opt/conda/lib/python3.7/site-packages/dgl/runtime/ir/executor.py", line 204, in run
    udf_ret = fn_data(src_data, edge_data, dst_data)
  File "/opt/conda/lib/python3.7/site-packages/dgl/runtime/scheduler.py", line 949, in _mfunc_wrapper
    return mfunc(ebatch)
  File "/data/KGAT-pytorch/model/KGAT.py", line 113, in att_score
    r_mul_h = torch.matmul(self.entity_user_embed(edges.src['id']), self.W_r)                       # (n_edge, relation_dim)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

**Comment by San-ctuary** [comment]
请问解决了吗  我也遇到这种问题，本地用cpu跑没问题，服务器上有gpu就有问题了
