### ISSUE TITLE
运行

### ISSUE THREAD

**Issue by Shodowelf** [LunaBlack/KGAT-pytorch#4]
你好，我在运行main_kgat.py时候，为什么报错 
File "C:\Users\zheny\Anaconda3\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。
还请解答

**Comment by LunaBlack** [comment]
Can you give more information, such as full error message?
Please check [environment requirements](https://github.com/LunaBlack/KGAT-pytorch#environment-requirement)

**Comment by Shodowelf** [comment]
谢谢您的回复，我再好好配一下环境，然后运行一下，如果出现问题，我在给您留言。
我还想请问一下，是不是配好环境之后，只要直接运行不同main.py,整个模型就能够跑起来。刚刚入手这方面，还有好多不懂之处，请多多指教，谢谢。

**Comment by LunaBlack** [comment]
Here is how to run different models: https://github.com/LunaBlack/KGAT-pytorch#run-the-codes, you can try it.

**Comment by Shodowelf** [comment]
Thank you very much.

**Comment by Shodowelf** [comment]
我已经根据您提供教程，将环境配好，并且版本也一致，然后在我运行main_kgat.py时，报了下面的错误：E:\kgg\venv\Scripts\python.exe E:/kgg/main_kgat.py
Traceback (most recent call last):
  File "E:/kgg/main_kgat.py", line 16, in <module>
    from model.KGAT import KGAT
  File "E:\kgg\model\KGAT.py", line 1, in <module>
    import dgl
  File "E:\kgg\venv\lib\site-packages\dgl\__init__.py", line 6, in <module>
    from . import function
  File "E:\kgg\venv\lib\site-packages\dgl\function\__init__.py", line 5, in <module>
    from .message import *
  File "E:\kgg\venv\lib\site-packages\dgl\function\message.py", line 8, in <module>
    from ..runtime import ir
  File "E:\kgg\venv\lib\site-packages\dgl\runtime\__init__.py", line 4, in <module>
    from . import scheduler
  File "E:\kgg\venv\lib\site-packages\dgl\runtime\scheduler.py", line 4, in <module>
    from .. import utils
  File "E:\kgg\venv\lib\site-packages\dgl\utils.py", line 8, in <module>
    from .base import DGLError
  File "E:\kgg\venv\lib\site-packages\dgl\base.py", line 6, in <module>
    from ._ffi.base import DGLError  # pylint: disable=unused-import
  File "E:\kgg\venv\lib\site-packages\dgl\_ffi\base.py", line 42, in <module>
    _LIB, _LIB_NAME = _load_lib()
  File "E:\kgg\venv\lib\site-packages\dgl\_ffi\base.py", line 34, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "E:\1219\anaconda\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

Process finished with exit code 1
还麻烦您要是有时间的话，帮忙看一下，这个错误如何修改，谢谢。

**Comment by LunaBlack** [comment]
Did you install cuda?
Can you show me your environments?

**Comment by Shodowelf** [comment]
我在pycharm下安装了
torch == 1.3.1
* dgl-cu90 == 0.4.1
* numpy == 1.15.4
* pandas == 0.23.1
* scipy == 1.1.0
* sklearn == 0.20.0
并没有install cuda,是因为cuda没有安装出现的问题吗？

**Comment by LunaBlack** [comment]
It might be. Please install cuda and try again.

**Comment by Shodowelf** [comment]
OK

**Comment by Shodowelf** [comment]
刚刚查了下，电脑已经装好了cuda了

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:04_Central_Daylight_Time_2018
Cuda compilation tools, release 10.0, V10.0.130
那应该不是cuda出了问题。

**Comment by LunaBlack** [comment]
The dgl-cu90 might be incompatible with cuda 10. You can try with dgl-cu100 or reinstall cuda 9.

**Comment by Shodowelf** [comment]
OK，我试试，这么晚还打扰您实在不好意思
